---
# tasks file for guacamole
# docker pull guacamole/guacamole
- name: Pull guacamole docker image
  shell: docker pull guacamole/guacamole

# docker pull guacamole/guacd
- name: Pull guacamole docker image
  shell: docker pull guacamole/guacd

- name: Get postgres for guacd
  shell: docker pull postgres

-name: Get sql init script for postgres
 shell: docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgres > /tmp/initdb.sql

- name: Start guacamole, postgres, and guacd
  shell: docker-compose up
